BackendMiniTask/Models/BaseEntity.cs
namespace BackendMiniTask.Models
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }
        public bool SoftDelete { get; set; }
    }
}

BackendMiniTask/Models/Slider.cs
namespace BackendMiniTask.Models
{
    public class Slider: BaseEntity
    {
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}

BackendMiniTask/ViewModels/Slider/SliderCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace BackendMiniTask.ViewModels.Slider
{
    public class SliderCreateVM
    {
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        [Required]
        public IFormFile? Image { get; set; }
    }
}

BackendMiniTask/ViewModels/Slider/SliderUpdateVM.cs
using System.ComponentModel.DataAnnotations;

namespace BackendMiniTask.ViewModels.Slider
{
    public class SliderUpdateVM
    {

        [Required]
        public string Title { get; set; }
        public string SubTitle { get; set; }

        public string Description { get; set; }

        public string Image { get; set; }
        public IFormFile? Photo { get; set; }
    }
}

BackendMiniTask/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BackendMiniTask.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BackendMiniTask/Areas/Admin/Controllers/SliderController.cs
using BackendMiniTask.DAL;
using BackendMiniTask.Helpers.Extentions;
using BackendMiniTask.Models;
using BackendMiniTask.ViewModels.Slider;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BackendMiniTask.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public SliderController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            var datas = await _context.Slider.ToListAsync();
            return View(datas);
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id <= 0) return BadRequest();
            var data = await _context.Slider.FirstOrDefaultAsync(m => m.Id == id);
            if (data == null) return NotFound();
            return View(data);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SliderCreateVM create)
        {
            if (!ModelState.IsValid) return View();
            if (!create.Image.CheckFileType("image/"))
            {
                ModelState.AddModelError("Image", "File must be Image Format");
                return View();
            }
            if (!create.Image.CheckFileSize(200))
            {

                ModelState.AddModelError("Image", "Max File Capacity mut be 300KB");
                return View();
            }

            string fileName = Guid.NewGuid().ToString() + "-" + create.Image.FileName;
            string path = Path.Combine(_env.WebRootPath, "assets", "images", fileName);
            await create.Image.SaveFileToLocalAsync(path);


            Slider slider = new()
            {
                Image = fileName,
                Title = create.Title,
                SubTitle = create.SubTitle,
                Description = create.Description,
            };
            await _context.Slider.AddAsync(slider);
            await _context.SaveChangesAsync();



            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();

            Slider existed = await _context.Slider.FirstOrDefaultAsync(s => s.Id == id);

            if (existed is null) return NotFound();

            SliderUpdateVM slideVM = new()
            {
                Image = existed.Image,
                Title = existed.Title,
                SubTitle = existed.SubTitle,
                Description = existed.Description,
            };

            return View(slideVM);

        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, SliderUpdateVM slideVM)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }
            Slider existed = await _context.Slider.FirstOrDefaultAsync(s => s.Id == id);

            if (existed is null) return NotFound();

            if (slideVM.Photo is not null)
            {
                if (!slideVM.Photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Image", "File must be Image Format");
                    return View(slideVM);
                }
                if (!slideVM.Photo.CheckFileSize(200))
                {

                    ModelState.AddModelError("Image", "Max File Capacity mut be 300KB");
                    return View(slideVM);
                }
                string newImage = await slideVM.Photo.CreateFileAsync(_env.WebRootPath, "assets", "images");
                existed.Image.DeleteFile(_env.WebRootPath, "assets", "images");
                existed.Image = newImage;

            }

            existed.Title = slideVM.Title;
            existed.Description = slideVM.Description;
            existed.SubTitle = slideVM.SubTitle;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();

            Slider slide = await _context.Slider.FirstOrDefaultAsync(s => s.Id == id);

            if (slide is null) return NotFound();

            slide.Image.DeleteFile(_env.WebRootPath, "assets", "images");

            _context.Slider.Remove(slide);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }
    }
}

BackendMiniTask/Controllers/HomeController.cs
using BackendMiniTask.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BackendMiniTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;
        public HomeController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var datas = await _context.Slider.ToListAsync();
            return View(datas);
        }
    }
}

BackendMiniTask/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

BackendMiniTask/Areas/Admin/Views/Slider/Create.cshtml
@using BackendMiniTask.ViewModels.Slider
@model SliderCreateVM

@{
    ViewData["Title"] = "Create";
}


<div class="container mt-5">
    <h3 class="text-center text-dark">Create New Slider</h3>
    <form class="forms-sample" method="post" asp-action="Create" enctype="multipart/form-data">
        <div class="form-group">

           <label>Title</label>
            <input asp-for="Title" class="form-control text-black" maxlength="50">
            <span class="text-danger" asp-validation-for="Title"></span>
            
            <label class="mt-4">SubTitle</label>
            <input asp-for="SubTitle" class="form-control text-black" maxlength="20">
            <span class="text-danger" asp-validation-for="SubTitle"></span>

            <label class="mt-4">Description</label>
            <input asp-for="Description" class="form-control text-black" maxlength="20">
            <span class="text-danger" asp-validation-for="Description"></span>
            
            <label class="mt-4">Image</label>
            <input asp-for="Image" class="form-control">
            <span class="text-danger" asp-validation-for="Image"></span>
        </div>


        <button type="submit" class="btn btn-primary mr-2">Submit</button>
        <a asp-action="Index" class="btn btn-primary text-white">Back</a>
    </form>
</div>

BackendMiniTask/Areas/Admin/Views/Slider/Detail.cshtml
@model Slider

<div class="container mt-5 mx-3">

    <p><b>Title</b>: @Model.Title</p>
    <p><b>Subtitle</b>: @Model.SubTitle</p>
    <img  src="~/assets/images/@Model.Image" width=378px; />

    <div class=mt-4>

        <a class="btn btn-primary" asp-area="Admin" asp-controller="Slider" asp-action="Index">Back</a>
        <a class="btn btn-primary" asp-area="Admin" asp-controller="Slider" asp-route-id="@Model.Id" asp-action="Update">Update</a>
        <a class="btn btn-danger" asp-area="Admin" asp-controller="Slider" asp-route-id="@Model.Id" asp-action="Delete">Delete</a>
    </div>
</div>

BackendMiniTask/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <a class="btn btn-success" asp-area="Admin" asp-controller="Slider" asp-action="Create">Create Slider</a>


            <table class="table table-striped">
                <thead>
                    <tr>
                        <th> Image </th>
                        <th> Title </th>
                        <th> Settings </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>

                            <td> <img src="~/assets/images/@item.Image" style="width:125px;height:75px;"> </td>
                            <td> @item.Title </td>
                            <td>
                                <a class="btn btn-info" asp-area="Admin" asp-controller="Slider" asp-route-id="@item.Id" asp-action="Detail">Detail</a>
                                <a class="btn btn-primary" asp-area="Admin" asp-controller="Slider" asp-route-id="@item.Id" asp-action="Update">Update</a>
                                <a class="btn btn-danger" asp-area="Admin" asp-controller="Slider" asp-route-id="@item.Id" asp-action="Delete">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

BackendMiniTask/Areas/Admin/Views/Slider/Update.cshtml
@using BackendMiniTask.ViewModels.Slider
@model SliderUpdateVM


<div class="container mt-5">
    <h3 class="text-center text-dark">Update Slider</h3>

     <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <img  src="~/assets/images/@Model.Image" style="width:200px; height:200px;object-fit:cover"/>
                    <input asp-for="Image" type="hidden" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Photo">Choose new Photo</label>
                    <input asp-for="Photo" class="form-control" placeholder="Photo">
                    <span class="text-danger" asp-validation-for="Photo"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input asp-for="Title" class="form-control" placeholder="Title">
                    <span class="text-danger" asp-validation-for="Title"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SubTitle">SubTitle</label>
                    <input asp-for="SubTitle" class="form-control" placeholder="SubTitle">
                    <span class="text-danger" asp-validation-for="SubTitle"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description">Description</label>
                    <input asp-for="Description" class="form-control" placeholder="Description">
                    <span class="text-danger" asp-validation-for="Description"></span>
                </div>

                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <a asp-action="Index" asp-controller="Slide" class="btn btn-light">Cancel</a>
            </form>
</div>